CREATE DATABASE Pclinics;

USE Pclinics;

CREATE TABLE Clinica (
	IdClinica INT PRIMARY KEY IDENTITY,
	RazaoSocial VARCHAR(250) NOT NULL,
	Endereco VARCHAR(200) NOT NULL
);

CREATE TABLE Dono (
	IdDono INT PRIMARY KEY IDENTITY,
	NomeDono VARCHAR(200) NOT NULL
);

CREATE TABLE TipoPet (
	IdTipoPet INT PRIMARY KEY IDENTITY,
	TituloPet VARCHAR(200) NOT NULL
);

CREATE TABLE Raca (
	IdRaca INT PRIMARY KEY IDENTITY,
	TituloRaca VARCHAR(200) NOT NULL,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet (IdTipoPet)
);

CREATE TABLE Veterinario (
	IdVeterinario INT PRIMARY KEY IDENTITY,
	NomeVeterinario VARCHAR(200) NOT NULL,
	CRMV VARCHAR(200) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica (IdClinica)
);

CREATE TABLE Pet (
	IdPet INT PRIMARY KEY IDENTITY,
	NomePet VARCHAR(200) NOT NULL,
	Telefone VARCHAR(200) NOT NULL,
	IdDono INT FOREIGN KEY REFERENCES Dono (IdDono),
	IdRaca INT FOREIGN KEY REFERENCES Raca (IdRaca)
);

CREATE TABLE Atendimento (
	IdAtendimento INT PRIMARY KEY IDENTITY,
	DataAtendimento VARCHAR(200) NOT NULL,
	Descricao VARCHAR(300) NOT NULL,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario (IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES Pet (IdPet)
);
